<?php
require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';require_permission($pdo,'create_orders');if(user_role($pdo)!=='client')redirect('/index.php');
$clientId=client_id_for_user($pdo,(int)current_user($pdo)['id']);$cartId=get_or_create_cart($pdo,$clientId);
$st=$pdo->prepare("SELECT ci.*,p.name,p.stock,p.selling_price,p.discount FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=?");$st->execute([$cartId]);$items=$st->fetchAll();if(!$items){flash('warning','Your cart is empty.');redirect('/client/cart.php');}
$st=$pdo->prepare("SELECT address FROM clients WHERE id=?");$st->execute([$clientId]);$address=$st->fetchColumn()?:'';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$shipping=trim($_POST['shipping_address']??'');if($shipping==='')$error='Shipping address is required.';else try{$pdo->beginTransaction();
$locked=$pdo->prepare("SELECT ci.product_id,ci.quantity,p.name,p.stock,p.selling_price,p.discount FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=? FOR UPDATE");$locked->execute([$cartId]);$items=$locked->fetchAll();$subtotal=0;foreach($items as $i){if($i['stock']<$i['quantity'])throw new RuntimeException('Not enough stock for '.$i['name']);$subtotal+=product_price($i)*$i['quantity'];}
$orderNo='ST-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$pdo->prepare("INSERT INTO orders(order_number,client_id,subtotal,total_amount,shipping_address,status) VALUES(?,?,?,?,?,'pending')")->execute([$orderNo,$clientId,$subtotal,$subtotal,$shipping]);$orderId=(int)$pdo->lastInsertId();
$oi=$pdo->prepare("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,discount,subtotal) VALUES(?,?,?,?,?,?,?)");$up=$pdo->prepare("UPDATE products SET stock=stock-? WHERE id=?");foreach($items as $i){$price=product_price($i);$oi->execute([$orderId,$i['product_id'],$i['name'],$i['quantity'],$price,$i['discount'],$price*$i['quantity']]);$up->execute([$i['quantity'],$i['product_id']]);}$pdo->prepare("DELETE FROM cart_items WHERE cart_id=?")->execute([$cartId]);$pdo->commit();flash('success','Order '.$orderNo.' created successfully.');redirect('/client/orders.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage()?:'Checkout failed.';}}
$active='cart';$pageTitle='Checkout';include __DIR__.'/../includes/header.php';?>
<div class="mb-4"><span class="eyebrow">CHECKOUT</span><h1 class="page-title">Complete Order</h1></div><div class="row g-4"><div class="col-lg-7"><div class="panel"><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><label class="form-label">Shipping Address</label><textarea class="form-control mb-4" name="shipping_address" rows="4" required><?=e($_POST['shipping_address']??$address)?></textarea><button class="btn btn-stare">Place Order</button> <a class="btn btn-outline-secondary" href="cart.php">Back to Cart</a></form></div></div><div class="col-lg-5"><div class="panel"><h2 class="h5">Order Summary</h2><?php $sum=0;foreach($items as $i){$line=product_price($i)*$i['quantity'];$sum+=$line;?><div class="d-flex justify-content-between border-bottom py-2"><span><?=e($i['name'])?> × <?=$i['quantity']?></span><strong><?=money($line)?></strong></div><?php }?><div class="d-flex justify-content-between pt-3"><strong>Total</strong><strong><?=money($sum)?></strong></div></div></div></div>
<?php include __DIR__.'/../includes/footer.php';?>
