<?php
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/functions.php';require_permission($pdo,'view_orders');$active='orders';$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT o.*,u.name client_name,u.email client_email,e.id employee_id,e_u.name employee_name FROM orders o JOIN clients c ON c.id=o.client_id JOIN users u ON u.id=c.user_id LEFT JOIN employees e ON e.id=o.employee_id LEFT JOIN users e_u ON e_u.id=e.user_id WHERE o.id=?");$st->execute([$id]);$order=$st->fetch();if(!$order)redirect('/admin/orders/index.php');
$st=$pdo->prepare("SELECT * FROM order_items WHERE order_id=?");$st->execute([$id]);$items=$st->fetchAll();
$employees=$pdo->query("SELECT e.id,u.name FROM employees e JOIN users u ON u.id=e.user_id WHERE u.status='active' ORDER BY u.name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST' && has_permission($pdo,'manage_orders')){verify_csrf();$newStatus=$_POST['status']??$order['status'];$employeeId=($_POST['employee_id']??'')!==''?(int)$_POST['employee_id']:null;$allowed=['pending','confirmed','processing','shipped','delivered','cancelled'];if(in_array($newStatus,$allowed,true)){$pdo->prepare("UPDATE orders SET status=?,employee_id=? WHERE id=?")->execute([$newStatus,$employeeId,$id]);flash('success','Order updated.');redirect('/admin/orders/view.php?id='.$id);}}
$pageTitle='Order '.$order['order_number'];include __DIR__.'/../../includes/header.php';?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><span class="eyebrow">ORDER DETAILS</span><h1 class="page-title">#<?=e($order['order_number'])?></h1></div><?=status_badge($order['status'])?></div>
<div class="row g-4"><div class="col-lg-8"><div class="panel"><div class="panel-head"><h2 class="h5 mb-0">Items</h2></div><div class="table-responsive"><table class="table stare-table"><thead><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Subtotal</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?=e($i['product_name'])?></td><td><?=$i['quantity']?></td><td><?=money($i['unit_price'])?></td><td><?=money($i['subtotal'])?></td></tr><?php endforeach;?></tbody></table></div><div class="order-total"><span>Total</span><strong><?=money($order['total_amount'])?></strong></div></div></div>
<div class="col-lg-4"><div class="panel mb-4"><h2 class="h5">Client</h2><p class="mb-1"><strong><?=e($order['client_name'])?></strong></p><p class="text-secondary small"><?=e($order['client_email'])?></p><p class="small"><?=e($order['shipping_address'])?></p></div>
<?php if(has_permission($pdo,'manage_orders')):?><div class="panel"><h2 class="h5">Manage</h2><form method="post"><?=csrf_field()?><label class="form-label">Status</label><select class="form-select mb-3" name="status"><?php foreach(['pending','confirmed','processing','shipped','delivered','cancelled'] as $s):?><option value="<?=$s?>" <?=$order['status']===$s?'selected':''?>><?=ucfirst($s)?></option><?php endforeach;?></select><label class="form-label">Employee</label><select class="form-select mb-3" name="employee_id"><option value="">Unassigned</option><?php foreach($employees as $e):?><option value="<?=$e['id']?>" <?=$order['employee_id']==$e['id']?'selected':''?>><?=e($e['name'])?></option><?php endforeach;?></select><button class="btn btn-stare w-100">Update Order</button></form></div><?php endif;?></div></div>
<?php include __DIR__.'/../../includes/footer.php';?>
