<?php
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/functions.php';
require_permission($pdo,'manage_users');$active='users';$pageTitle='Users';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['id']??0);$status=$_POST['status']??'active';if(in_array($status,['active','pending','blocked'],true)){if($id===(int)current_user($pdo)['id'] && $status!=='active'){flash('danger','You cannot block your own account.');}else{$pdo->prepare("UPDATE users SET status=? WHERE id=?")->execute([$status,$id]);flash('success','User status updated.');}}redirect('/admin/users/index.php');}
$rows=$pdo->query("SELECT u.id,u.name,u.email,u.status,u.created_at,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id DESC")->fetchAll();
include __DIR__.'/../../includes/header.php';?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><span class="eyebrow">SECURITY</span><h1 class="page-title">Users</h1><p class="text-secondary mb-0">Manage account status and review assigned roles.</p></div></div>
<div class="panel"><div class="table-responsive"><table class="table stare-table align-middle"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>
<?php foreach($rows as $u):?><tr><td><strong><?=e($u['name'])?></strong><div class="small text-secondary"><?=e($u['email'])?></div></td><td><?=e(ucfirst($u['role_name']))?></td><td><?=status_badge($u['status'])?></td><td><?=e(date('Y-m-d',strtotime($u['created_at'])))?></td><td><form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="hidden" name="id" value="<?=$u['id']?>"><select class="form-select form-select-sm" name="status"><option value="active" <?=$u['status']==='active'?'selected':''?>>Active</option><option value="pending" <?=$u['status']==='pending'?'selected':''?>>Pending</option><option value="blocked" <?=$u['status']==='blocked'?'selected':''?>>Blocked</option></select><button class="btn btn-sm btn-outline-secondary">Save</button></form></td></tr><?php endforeach;?>
</tbody></table></div></div><?php include __DIR__.'/../../includes/footer.php'; ?>
