<?php
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/functions.php';require_permission($pdo,'manage_employees');$active='employees';$id=(int)($_GET['id']??0);
$row=['name'=>'','email'=>'','phone'=>'','address'=>'','department'=>'','position'=>'','salary'=>'0','hire_date'=>'','status'=>'active','role_id'=>''];$userId=0;
if($id){$st=$pdo->prepare("SELECT e.*,u.name,u.email,u.status user_status,u.role_id FROM employees e JOIN users u ON u.id=e.user_id WHERE e.id=?");$st->execute([$id]);$found=$st->fetch();if(!$found)redirect('/admin/employees/index.php');$row=$found;$userId=(int)$found['user_id'];}
$roles=$pdo->query("SELECT id,name FROM roles WHERE name IN('employee','admin') ORDER BY name")->fetchAll();$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$password=$_POST['password']??'';$roleId=(int)($_POST['role_id']??0);
if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$roleId)$error='Name, email and role are required.';
else try{$pdo->beginTransaction();$status=$_POST['status']??'active';if($id){$pdo->prepare("UPDATE users SET name=?,email=?,role_id=?,status=? WHERE id=?")->execute([$name,$email,$roleId,$status,$userId]);if($password!=='')$pdo->prepare("UPDATE users SET password=? WHERE id=?")->execute([password_hash($password,PASSWORD_DEFAULT),$userId]);$pdo->prepare("UPDATE employees SET phone=?,address=?,department=?,position=?,salary=?,hire_date=?,status=? WHERE id=?")->execute([trim($_POST['phone']??''),trim($_POST['address']??''),trim($_POST['department']??''),trim($_POST['position']??''),(float)($_POST['salary']??0),($_POST['hire_date']??'')?:null,$status==='active'?'active':'inactive',$id]);}else{$pdo->prepare("INSERT INTO users(name,email,password,role_id,status) VALUES(?,?,?,?,?)")->execute([$name,$email,password_hash($password?:'password',PASSWORD_DEFAULT),$roleId,$status]);$userId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO employees(user_id,phone,address,department,position,salary,hire_date,status) VALUES(?,?,?,?,?,?,?,?)")->execute([$userId,trim($_POST['phone']??''),trim($_POST['address']??''),trim($_POST['department']??''),trim($_POST['position']??''),(float)($_POST['salary']??0),($_POST['hire_date']??'')?:null,$status==='active'?'active':'inactive']);}$pdo->commit();flash('success','Employee saved.');redirect('/admin/employees/index.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Could not save employee. Email may already exist.';}}
$pageTitle=$id?'Edit Employee':'Add Employee';include __DIR__.'/../../includes/header.php';?>
<div class="mb-4"><span class="eyebrow">PEOPLE</span><h1 class="page-title"><?=$id?'Edit':'Add'?> Employee</h1></div><div class="panel form-panel"><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="<?=e($row['name'])?>" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($row['email'])?>" required></div><div class="col-md-4"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?=e($row['phone'])?>"></div><div class="col-md-8"><label class="form-label">Address</label><input class="form-control" name="address" value="<?=e($row['address'])?>"></div><div class="col-md-4"><label class="form-label">Department</label><input class="form-control" name="department" value="<?=e($row['department'])?>"></div><div class="col-md-4"><label class="form-label">Position</label><input class="form-control" name="position" value="<?=e($row['position'])?>"></div><div class="col-md-4"><label class="form-label">Salary</label><input class="form-control" type="number" step=".01" min="0" name="salary" value="<?=e($row['salary'])?>"></div><div class="col-md-4"><label class="form-label">Hire Date</label><input class="form-control" type="date" name="hire_date" value="<?=e($row['hire_date'])?>"></div><div class="col-md-4"><label class="form-label">Role</label><select class="form-select" name="role_id"><?php foreach($roles as $r):?><option value="<?=$r['id']?>" <?=$row['role_id']==$r['id']?'selected':''?>><?=e(ucfirst($r['name']))?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" <?=$row['status']==='active'?'selected':''?>>Active</option><option value="pending" <?=$row['status']==='pending'?'selected':''?>>Pending</option><option value="blocked" <?=$row['status']==='blocked'?'selected':''?>>Blocked</option></select></div><div class="col-md-6"><label class="form-label">Password <?=$id?'(optional)':''?></label><input class="form-control" type="password" name="password" <?=$id?'':'required'?>></div></div><div class="mt-4"><button class="btn btn-stare">Save Employee</button> <a class="btn btn-outline-secondary" href="index.php">Cancel</a></div></form></div><?php include __DIR__.'/../../includes/footer.php';?>
