<?php
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/functions.php';require_permission($pdo,'view_reports');$active='reports';$pageTitle='Reports';
$revenue=(float)$pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE status NOT IN('cancelled')")->fetchColumn();
$avg=(float)$pdo->query("SELECT COALESCE(AVG(total_amount),0) FROM orders WHERE status NOT IN('cancelled')")->fetchColumn();
$top=$pdo->query("SELECT oi.product_name,SUM(oi.quantity) qty,SUM(oi.subtotal) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status<>'cancelled' GROUP BY oi.product_id,oi.product_name ORDER BY qty DESC LIMIT 10")->fetchAll();
$monthly=$pdo->query("SELECT DATE_FORMAT(created_at,'%Y-%m') month,COUNT(*) orders,SUM(total_amount) revenue FROM orders WHERE status<>'cancelled' GROUP BY month ORDER BY month DESC LIMIT 6")->fetchAll();include __DIR__.'/../../includes/header.php';?>
<div class="mb-4"><span class="eyebrow">ANALYTICS</span><h1 class="page-title">Reports</h1></div><div class="row g-3 mb-4"><div class="col-md-4"><div class="stat-card"><div class="text-secondary">Revenue</div><div class="stat-value"><?=money($revenue)?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="text-secondary">Average Order</div><div class="stat-value"><?=money($avg)?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="text-secondary">Products Sold</div><div class="stat-value"><?=number_format((int)$pdo->query("SELECT COALESCE(SUM(quantity),0) FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.status<>'cancelled'")->fetchColumn())?></div></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="panel"><div class="panel-head"><h2 class="h5 mb-0">Top Products</h2></div><table class="table stare-table"><thead><tr><th>Product</th><th>Qty</th><th>Revenue</th></tr></thead><tbody><?php foreach($top as $r):?><tr><td><?=e($r['product_name'])?></td><td><?=$r['qty']?></td><td><?=money($r['revenue'])?></td></tr><?php endforeach;?></tbody></table></div></div><div class="col-lg-5"><div class="panel"><div class="panel-head"><h2 class="h5 mb-0">Monthly Summary</h2></div><table class="table stare-table"><thead><tr><th>Month</th><th>Orders</th><th>Revenue</th></tr></thead><tbody><?php foreach($monthly as $r):?><tr><td><?=e($r['month'])?></td><td><?=$r['orders']?></td><td><?=money($r['revenue'])?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php include __DIR__.'/../../includes/footer.php';?>
