<?php
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/functions.php';require_permission($pdo,'manage_clients');$active='clients';$id=(int)($_GET['id']??0);
$row=['name'=>'','email'=>'','phone'=>'','address'=>'','gender'=>'other','age'=>'','status'=>'active','password'=>''];$userId=0;
if($id){$st=$pdo->prepare("SELECT c.*,u.name,u.email,u.status user_status FROM clients c JOIN users u ON u.id=c.user_id WHERE c.id=?");$st->execute([$id]);$found=$st->fetch();if(!$found)redirect('/admin/clients/index.php');$row=$found;$userId=(int)$found['user_id'];}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$password=$_POST['password']??'';
if(strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL))$error='Name and valid email are required.';
else try{$pdo->beginTransaction();if($id){$sql="UPDATE users SET name=?,email=?,status=? WHERE id=?";$pdo->prepare($sql)->execute([$name,$email,$_POST['status']??'active',$userId]);if($password!=='')$pdo->prepare("UPDATE users SET password=? WHERE id=?")->execute([password_hash($password,PASSWORD_DEFAULT),$userId]);$pdo->prepare("UPDATE clients SET phone=?,address=?,gender=?,age=?,status=? WHERE id=?")->execute([trim($_POST['phone']??''),trim($_POST['address']??''),$_POST['gender']??'other',($_POST['age']??'')!==''?(int)$_POST['age']:null,$_POST['status']??'active',$id]);}else{$role=(int)$pdo->query("SELECT id FROM roles WHERE name='client'")->fetchColumn();$pdo->prepare("INSERT INTO users(name,email,password,role_id,status) VALUES(?,?,?,?,?)")->execute([$name,$email,password_hash($password?:'password',PASSWORD_DEFAULT),$role,'active']);$userId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO clients(user_id,phone,address,gender,age) VALUES(?,?,?,?,?)")->execute([$userId,trim($_POST['phone']??''),trim($_POST['address']??''),$_POST['gender']??'other',($_POST['age']??'')!==''?(int)$_POST['age']:null]);}$pdo->commit();flash('success','Client saved.');redirect('/admin/clients/index.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Could not save client. Email may already exist.';}}
$pageTitle=$id?'Edit Client':'Add Client';include __DIR__.'/../../includes/header.php';?>
<div class="mb-4"><span class="eyebrow">PEOPLE</span><h1 class="page-title"><?=$id?'Edit':'Add'?> Client</h1></div><div class="panel form-panel"><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="<?=e($row['name'])?>" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($row['email'])?>" required></div><div class="col-md-4"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?=e($row['phone'])?>"></div><div class="col-md-8"><label class="form-label">Address</label><input class="form-control" name="address" value="<?=e($row['address'])?>"></div><div class="col-md-4"><label class="form-label">Gender</label><select class="form-select" name="gender"><option value="male" <?=$row['gender']==='male'?'selected':''?>>Male</option><option value="female" <?=$row['gender']==='female'?'selected':''?>>Female</option><option value="other" <?=$row['gender']==='other'?'selected':''?>>Other</option></select></div><div class="col-md-4"><label class="form-label">Age</label><input class="form-control" type="number" min="1" max="120" name="age" value="<?=e($row['age'])?>"></div><div class="col-md-4"><label class="form-label">Account Status</label><select class="form-select" name="status"><option value="active" <?=$row['status']==='active'?'selected':''?>>Active</option><option value="inactive" <?=$row['status']==='inactive'?'selected':''?>>Inactive</option></select></div><div class="col-md-6"><label class="form-label">Password <?=$id?'(optional)':''?></label><input class="form-control" type="password" name="password" <?=$id?'':'required'?>></div></div><div class="mt-4"><button class="btn btn-stare">Save Client</button> <a class="btn btn-outline-secondary" href="index.php">Cancel</a></div></form></div><?php include __DIR__.'/../../includes/footer.php';?>
